title: Data at Sea
description: A community-driven, GitHub Pages-hosted resource aggregate focused on deep ocean science data management across the expedition lifecycle. Built for easy community contribution via Discussion, Issues, and Pull Requests
color_scheme: ocean

url: https://schmidtocean.github.io/data-at-sea

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
